dependencies:
  - name: inventory-management-ui-mo
    version: 1.0.0-8
    repository: >-
      http://artifactory.mooc-cpat-ocp01-c-750890-afb9c6047b062b44e3f1b3ecfeba4309-0000.us-east.containers.appdomain.cloud/artifactory/generic-local/cpat-mooc-team-one/
